# fly.toml app configuration file generated for readme-backend on 2024-02-25T16:43:29-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'readmeapp'
primary_region = 'gru'
console_command = '/rails/bin/rails console'

[build]

[deploy]
   #pre = ["bundle install", "rails db:migrate", "rails db:seed", rails db:prepare]
   release_command = './bin/rails db:seed'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.status]
    port = 4000
    type = 'http'
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [checks.status.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'

# Add the environment variable for database environment check disable
#[env]
#  DISABLE_DATABASE_ENVIRONMENT_CHECK = "1"